---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-2.13.4-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    identityTrustAnchorsPEM: |-
      -----BEGIN CERTIFICATE-----
      MIIBjzCCATSgAwIBAgIRAIGOM0od6xhGd75liNzODfgwCgYIKoZIzj0EAwIwJTEj
      MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwNjA2MDAw
      NjM3WhcNMzMwNjAzMDAwNjM3WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
      c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDAECzk6m5yFcjtL
      fd825RPFAEoPE4/BNHDjgmX/Bfhg7gpSvZg3tw+rLfla41QUFcV419qSTZp0PzCo
      wLwjwF+jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
      A1UdDgQWBBTsJqZY+pP5bd4m/l4P1QVGzG5jazAKBggqhkjOPQQDAgNJADBGAiEA
      4Yy84YiP7YkKAF7cX37ZF+KrPOowizewNGtu25+/4ZMCIQDfBGqk8Fw80N2ooWLC
      g7FLhGZ4+VMf1sWO7SAuyCKiXg==
      -----END CERTIFICATE-----
    identity:
      issuer:
        tls: 
          crtPEM: |-
            -----BEGIN CERTIFICATE-----
            MIIBszCCAVmgAwIBAgIRAKee2+XWF8yku6glKbzUOS0wCgYIKoZIzj0EAwIwJTEj
            MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMwNjA2MDAw
            NzU3WhcNMjQwNjA1MDAwNzU3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJk
            LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATChHgbCX1A
            vg7twWEfiniQqsrj3P/46xPo+Mpwy1/hNK3jzUuq0Is4TuujQqWFhyEVtYDiKKjm
            PBeOSfB2o7Rso2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIB
            ADAdBgNVHQ4EFgQUFRDOpG/WIgJd4hWm3NVLx0iF23EwHwYDVR0jBBgwFoAU7Cam
            WPqT+W3eJv5eD9UFRsxuY2swCgYIKoZIzj0EAwIDSAAwRQIgVGqJcnfbHYjLT4tq
            ZiVqaI4W6zd5iSVqTe0G/A3PV8QCIQDhmQ5rmbX4xBaEXNG3zR/xeMyT0f9d33f1
            jfbhjyHVjw==
            -----END CERTIFICATE-----
          keyPEM: |-
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIN3t9nqpE9i8qhFffzCGTQ9N2wYDdqiss1vJyPf3X+wGoAoGCCqGSM49
            AwEHoUQDQgAEwoR4Gwl9QL4O7cFhH4p4kKrK49z/+OsT6PjKcMtf4TSt481LqtCL
            OE7ro0KlhYchFbWA4iio5jwXjknwdqO0bA==
            -----END EC PRIVATE KEY-----
