---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: ${releaseNamespace}
spec:
  interval: 1h0m0s
  type: obi
  url: "${helmMirrorURL:=oci://ghcr.io/weaveworks/charts}"
  timeout 2m
