---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: codecentric.github.io
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=https://codecentric.github.io/helm-charts}"
