---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: ${releaseNamespace}
      version: 2.12.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: keda
  valuesFrom:
    - kind: ConfigMap
      name: keda-2.12.0-defaults
  targetNamespace: ${releaseNamespace}
