---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-15.1.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    ingress:
      enabled: true
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "500m"
        memory: "1024Mi"
