---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: weave-gitops
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      version: 4.0.8 
  interval: 15s  
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: weave-gitops
  valuesFrom:
    - kind: ConfigMap
      name: weave-gitops-0.11.0-d2iq-defaults
  targetNamespace: ${releaseNamespace}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops-ingress
  namespace: ${releaseNamespace}
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: velero-minio
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: weave-gitops
            port:
              number: 9001
        path: /
        pathType: Prefix
