---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-crds
      sourceRef:
        kind: HelmRepository
        name: helm.linkerd.io
        namespace: ${releaseNamespace}
      version: 1.6.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-crds
  targetNamespace: ${releaseNamespace}

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: helm.linkerd.io
        namespace: ${releaseNamespace}
      version: 1.12.4
  dependsOn:
    - name: linkerd-crds
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-control-plane
  valuesFrom:
    - kind: ConfigMap
      name: linkerd-2.13.4-defaults
  targetNamespace: linkerd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-multicluster
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-multicluster
      sourceRef:
        kind: HelmRepository
        name: helm.linkerd.io
        namespace: ${releaseNamespace}
      version: 30.7.3
  dependsOn:
    - name: linkerd-control-plane
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-multicluster
  targetNamespace: linkerd-multicluster
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: helm.linkerd.io
        namespace: ${releaseNamespace}
      version: 30.8.3
  dependsOn:
    - name: linkerd-crds
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: linkerd-viz
  targetNamespace: linkerd
